# Generated by Django 5.0.6 on 2024-05-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchlists", "0002_alter_watchlist_symbol_delete_symbol"),
    ]

    operations = [
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField()),
                ("name", models.CharField()),
                ("type", models.CharField()),
                ("region", models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
