# Generated by Django 5.0.6 on 2024-05-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchlists", "0003_symbol_alter_watchlist_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
